name: CD
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  ios:
    name: iOS CI/CD
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 12.4

      - name: Prepare signing
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          run: |
            # create variables
            CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
            PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
            KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

            # import certificate and provisioning profile from secrets
            echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
            echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH

            # create temporary keychain
            security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
            security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
            security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

            # import certificate to keychain
            security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
            security list-keychain -d user -s $KEYCHAIN_PATH

            # apply provisioning profile
            mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
            cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
      - name: Set up Flutter
        uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'stable' # 'dev', 'alpha', 'master', default to: 'stable'
          # flutter-version: '1.22.x' # you can also specify exact version of flutter

      - name: Flutter doctor
        run: flutter doctor

      - name: Build IPA
        env:
          FS_KEYCHAIN_PASS: ${{ secrets.FS_KEYCHAIN_PASS }}
        run: |
          echo "Unlocking keychain"
          security unlock-keychain -p "$FS_KEYCHAIN_PASS" ~/Library/Keychains/build.keychain
          # Important, just in case the build takes longer than the default 300s timeout
          # Otherwise the build will freeze at signing the frameworks if the keychain is locked
          echo "Increasing keychain auto lock timeout"
          security set-keychain-settings -lut 1800 ~/Library/Keychains/build.keychain
          flutter build ipa --release --export-options-plist=ios/ExportOptions.plist
          echo "Locking keychain"
          security lock-keychain ~/Library/Keychains/build.keychain
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v1
        with:
          name: release-ipa
          path: ./build/ios/ipa/flutter_github_actions_basics.ipa

      - name: Publishing app to TestFlight
        env:
          FS_APPLE_ID_USERNAME: ${{ secrets.FS_APPLE_ID_USERNAME }}
          FS_APPLE_ID_APP_SPECIFIC_PASS: ${{ secrets.FS_APPLE_ID_APP_SPECIFIC_PASS }}
          FS_IPA_PATH: ./build/ios/ipa/flutter_github_actions_basics.ipa
        run: |
          xcrun altool --upload-app -t ios -f "$FS_IPA_PATH" -u "$FS_APPLE_ID_USERNAME" -p "$FS_APPLE_ID_APP_SPECIFIC_PASS"
  build_ios:
    name: Build Flutter (iOS)
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ["platform=iOS Simulator,OS=12"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter clean
      - run: flutter pub get
      - name: Install tools
        run: |
          flutter pub get
          cd ./ios && pod install
          mkdir -p /Users/runner/work/Documents/Cyberslovo/cd
          ln -s ios/Runner/GoogleService-Info.plist /Users/runner/work/Documents/Cyberslovo/cd/GoogleService-Info.plist
      - run: flutter build ios --release --no-codesign
#        It's for Faslu
