name: CD
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  ios:
    name: iOS CI/CD
    needs: code-analysis-and-testing
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 12.4

      - name: Prepare signing
        env:
          FS_KEYCHAIN_PASS: ${{ secrets.FS_KEYCHAIN_PASS }}
          FS_P12_FILE: ${{ secrets.FS_P12_FILE }}
          FS_P12_PASS: ${{ secrets.FS_P12_PASS }}
          FS_PROV_FILE: ${{ secrets.FS_PROV_FILE }}
        run: |
          echo "Convert base64 strings to files"
          echo "$FS_PROV_FILE" >> prov.temp.txt
          echo "$FS_P12_FILE ">> cert.temp.txt
          base64 --decode prov.temp.txt > prov.temp.mobileprovision
          base64 --decode cert.temp.txt > cert.temp.p12
          echo "Copy provisioning file to the correct locations"
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp prov.temp.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/prov.mobileprovision
          echo "Create a new keychain & import p12 certificate"
          security create-keychain -p "$FS_KEYCHAIN_PASS" build.keychain
          security import cert.temp.p12 -t agg -k ~/Library/Keychains/build.keychain -P "$FS_P12_PASS" -A
          echo "Set new keychain as a default"
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p "$FS_KEYCHAIN_PASS" ~/Library/Keychains/build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "$FS_KEYCHAIN_PASS" ~/Library/Keychains/build.keychain
          echo "Clean up temp files"
          rm *.temp.*
      - name: Set up Flutter
        uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'stable' # 'dev', 'alpha', 'master', default to: 'stable'
          # flutter-version: '1.22.x' # you can also specify exact version of flutter

      - name: Flutter doctor
        run: flutter doctor

      - name: Build IPA
        env:
          FS_KEYCHAIN_PASS: ${{ secrets.FS_KEYCHAIN_PASS }}
        run: |
          echo "Unlocking keychain"
          security unlock-keychain -p "$FS_KEYCHAIN_PASS" ~/Library/Keychains/build.keychain
          # Important, just in case the build takes longer than the default 300s timeout
          # Otherwise the build will freeze at signing the frameworks if the keychain is locked
          echo "Increasing keychain auto lock timeout"
          security set-keychain-settings -lut 1800 ~/Library/Keychains/build.keychain
          flutter build ipa --release --export-options-plist=ios/ExportOptions.plist
          echo "Locking keychain"
          security lock-keychain ~/Library/Keychains/build.keychain
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v1
        with:
          name: release-ipa
          path: ./build/ios/ipa/flutter_github_actions_basics.ipa

      - name: Publishing app to TestFlight
        env:
          FS_APPLE_ID_USERNAME: ${{ secrets.FS_APPLE_ID_USERNAME }}
          FS_APPLE_ID_APP_SPECIFIC_PASS: ${{ secrets.FS_APPLE_ID_APP_SPECIFIC_PASS }}
          FS_IPA_PATH: ./build/ios/ipa/flutter_github_actions_basics.ipa
        run: |
          xcrun altool --upload-app -t ios -f "$FS_IPA_PATH" -u "$FS_APPLE_ID_USERNAME" -p "$FS_APPLE_ID_APP_SPECIFIC_PASS"
  build_ios:
    name: Build Flutter (iOS)
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ["platform=iOS Simulator,OS=12"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter clean
      - run: flutter pub get
      - name: Install tools
        run: |
          flutter pub get
          cd ./ios && pod install
          mkdir -p /Users/runner/work/Documents/Cyberslovo/cd
          ln -s ios/Runner/GoogleService-Info.plist /Users/runner/work/Documents/Cyberslovo/cd/GoogleService-Info.plist
      - run: flutter build ios --release --no-codesign
#        It's for Faslu
